# Generated by Django 5.0.1 on 2024-01-06 21:07

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('phone_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number.')])),
                ('message', models.TextField()),
                ('time_of_submit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('botanical_name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('Active_compound', models.CharField(max_length=255)),
                ('related_diseae', models.CharField(max_length=255)),
                ('plant_image', models.ImageField(upload_to=myapp.models.img_plant)),
                ('part_used', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('time_of_add_plant', models.DateTimeField(auto_now_add=True)),
                ('reference_detail', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Phytochemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('struture', models.TextField()),
                ('molecular_weight', models.FloatField()),
                ('formula', models.CharField(max_length=255)),
                ('disease_association', models.CharField(max_length=255)),
                ('bioactivity', models.CharField(max_length=255)),
                ('struture_image', models.ImageField(upload_to=myapp.models.img_chem)),
                ('description_compound', models.TextField()),
                ('time_of_add', models.DateTimeField(auto_now_add=True)),
                ('plant_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phyto', to='myapp.plant')),
            ],
        ),
    ]
