# Generated by Django 5.0.1 on 2024-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcprop',
            name='hydrogen_donor',
            field=models.CharField(blank=True, default='Not available', max_length=255, null=True),
        ),
    ]
