# Generated by Django 5.0.1 on 2024-02-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mcprop_hydrogen_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcprop',
            name='num_hydro_donor',
        ),
    ]
