# Generated by Django 5.0.1 on 2024-02-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_phytochemical_referenceplant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phytochemical',
            old_name='referenceplant',
            new_name='reference_paper',
        ),
    ]
