# Generated by Django 5.0.1 on 2024-02-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_referenceplant_phytochemical_reference_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phytochemical',
            name='admeproperties',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.admeprop'),
        ),
        migrations.AlterField(
            model_name='phytochemical',
            name='dkproperties',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dkprop'),
        ),
        migrations.AlterField(
            model_name='phytochemical',
            name='mkproperties',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mcprop'),
        ),
        migrations.AlterField(
            model_name='phytochemical',
            name='reference_paper',
            field=models.ManyToManyField(blank=True, to='myapp.reference'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='phytochemical_value',
            field=models.ManyToManyField(blank=True, to='myapp.phytochemical'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='referenceplant',
            field=models.ManyToManyField(blank=True, to='myapp.reference'),
        ),
    ]
