# Generated by Django 5.0.1 on 2024-02-06 11:05

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_phytochemical_admeproperties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytochemical',
            name='chem_image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.img_chem),
        ),
        migrations.AddField(
            model_name='phytochemical',
            name='pubchem_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
