# Generated by Django 5.0.1 on 2024-02-06 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_phytochemical_chem_image_phytochemical_pubchem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phytochemical',
            name='admeproperties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.admeprop'),
        ),
        migrations.AlterField(
            model_name='phytochemical',
            name='dkproperties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dkprop'),
        ),
        migrations.AlterField(
            model_name='phytochemical',
            name='mkproperties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mcprop'),
        ),
    ]
