# Generated by Django 3.2.20 on 2024-01-06 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240105_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='Active_compound',
            new_name='active_compound',
        ),
    ]
