# Generated by Django 5.0.1 on 2024-02-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_phytochemical_admeproperties_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='active_compound',
            new_name='groups',
        ),
    ]
