# Generated by Django 5.0.1 on 2024-02-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_active_compound_plant_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phytochemical',
            old_name='external_identifiers',
            new_name='molecular_formula',
        ),
    ]
