# Generated by Django 5.0.1 on 2024-02-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_mcprop_impaat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcprop',
            name='Molprot',
            field=models.CharField(blank=True, default='Not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcprop',
            name='chembl',
            field=models.CharField(blank=True, default='Not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcprop',
            name='impaat',
            field=models.CharField(blank=True, default='Not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcprop',
            name='pubchem',
            field=models.CharField(blank=True, default='Not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcprop',
            name='surecheml',
            field=models.CharField(blank=True, default='Not available', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcprop',
            name='zinc',
            field=models.CharField(blank=True, default='Not available', max_length=255, null=True),
        ),
    ]
