# Generated by Django 5.0.1 on 2024-02-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_external_identifiers_phytochemical_molecular_formula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phytochemical',
            old_name='classyfire_kingdom',
            new_name='iupac_name',
        ),
        migrations.RemoveField(
            model_name='phytochemical',
            name='classyfire_superclass',
        ),
        migrations.AlterField(
            model_name='phytochemical',
            name='molecular_formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
