# Generated by Django 5.0.1 on 2024-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_mcprop_molprot_alter_mcprop_chembl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcprop',
            name='iupac_name',
            field=models.CharField(blank=True, default='Not available', max_length=555, null=True),
        ),
    ]
