# Generated by Django 5.0.1 on 2024-02-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_classyfire_kingdom_phytochemical_iupac_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phytochemical',
            old_name='np_classifier_biosynthetic_pathway',
            new_name='chembl_id',
        ),
        migrations.RenameField(
            model_name='phytochemical',
            old_name='classyfire_class',
            new_name='kegg_id',
        ),
        migrations.RenameField(
            model_name='phytochemical',
            old_name='classyfire_subclass',
            new_name='molecular_weight',
        ),
    ]
