# Generated by Django 5.0.1 on 2024-02-26 15:52

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_mcprop_iupac_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Not available', max_length=255, null=True)),
                ('score', models.CharField(blank=True, default='Not available', max_length=255, null=True)),
                ('iupac_name', models.CharField(blank=True, default='Not available', max_length=555, null=True)),
                ('kegg', models.CharField(blank=True, default='Not available', max_length=255, null=True)),
                ('dock_im', models.CharField(blank=True, default='Not available', max_length=255, null=True)),
                ('dock_image', models.ImageField(blank=True, default='Not available', null=True, upload_to=myapp.models.img_dock)),
            ],
        ),
    ]
