# Generated by Django 5.0.1 on 2024-02-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytochemical',
            name='target_prop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.target'),
        ),
    ]
