# Generated by Django 5.0.1 on 2024-02-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_phytochemical_target_prop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phytochemical',
            old_name='target_prop',
            new_name='target_propper',
        ),
    ]
