# Generated by Django 5.0.1 on 2024-02-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_target_prop_phytochemical_target_propper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target_reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dock_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('dock_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='target',
            name='dock_reference',
            field=models.ManyToManyField(blank=True, to='myapp.target_reference'),
        ),
    ]
